CREATE TABLE "STORE" (
	"STORE_NUM"	int		NOT NULL,
	"ID"	varchar2(20)		NOT NULL,
	"CLASSIFY"	varchar2(10)		NOT NULL,
	"NAME"	varchar2(100)		NOT NULL,
	"PHONE"	varchar2(20)		NOT NULL,
	"CITYCODE"	varchar2(100)		NOT NULL,
	"DISTRICTCODE"	varchar2(100)		NOT NULL,
	"ADDRESS"	varchar2(100)		NOT NULL,
	"MENU"	varchar2(2000)		NOT NULL,
	"TIME"	varchar2(100)		NOT NULL,
	"RESERVING"	char(1)		NULL,
	"ETC"	varchar2(100)		NOT NULL,
	"PWD"	varchar2(20)		NOT NULL,
	"COUNT"	int		NOT NULL,
	"PICTURE"	varchar2(3000)		NULL
);

CREATE TABLE "MEMBER" (
	"ID"	varchar2(20)		NOT NULL,
	"PWD"	varchar2(30)		NOT NULL,
	"EMAIL"	varchar2(100)		NOT NULL,
	"CLASSIFY"	int		NOT NULL,
	"REGDATE"	DATE		NOT NULL
);

CREATE TABLE "REVIEW" (
	"REVIEW_NUM"	int		NOT NULL,
	"STORE_NUM"	int		NOT NULL,
	"ID"	varchar2(20)		NOT NULL,
	"MENU"	varchar2(2000)		NOT NULL,
	"STAR"	number(2,1)		NOT NULL,
	"CONTENT"	varchar2(2000)		NOT NULL,
	"REVISIT"	char(1)		NULL,
	"REGDATE"	DATE		NOT NULL,
	"PICTURE"	varchar2(3000)		NULL
);

CREATE TABLE "REST_CAT" (
	"STORE_NUM"	int		NOT NULL,
	"SITUATION1"	char(1)		NULL,
	"SITUATION2"	char(1)		NULL,
	"SITUATION3"	char(1)		NULL,
	"TIMESLOT1"	char(1)		NULL,
	"TIMESLOT2"	char(1)		NULL,
	"TIMESLOT3"	char(1)		NULL,
	"TIMESLOT4"	char(1)		NULL,
	"TYPE1"	char(1)		NULL,
	"TYPE2"	char(1)		NULL,
	"TYPE3"	char(1)		NULL,
	"TYPE4"	char(1)		NULL
);

CREATE TABLE "RESERVE" (
	"STORE_NUM"	int		NOT NULL,
	"ID"	varchar2(20)		NOT NULL,
	"RESERVE_NAME"	varchar2(20)		NOT NULL,
	"RES_DATE"	timestamp		NOT NULL,
	"PHONE"	varchar2(20)		NOT NULL
);

CREATE TABLE "CAFE_CAT" (
	"STORE_NUM"	int		NOT NULL,
	"SITUATION1"	char(1)		NULL,
	"SITUATION2"	char(1)		NULL,
	"SITUATION3"	char(1)		NULL,
	"TIMESLOT"	char(1)		NULL,
	"MOOD1"	char(1)		NULL,
	"MOOD2"	char(1)		NULL,
	"MOOD3"	char(1)		NULL,
	"SIZE1"	char(1)		NULL,
	"SIZE2"	char(1)		NULL,
	"SIZE3"	char(1)		NULL
);

CREATE TABLE "WARNING" (
	"WARNING_NUM"	int		NOT NULL,
	"REVIEW_NUM"	int		NOT NULL,
	"REASON"	varchar2(100)		NOT NULL,
	"REPORTER"	varchar2(20)		NOT NULL,
	"REGDATE"	DATE		NOT NULL
);

CREATE TABLE "NOTICE" (
	"NOTICE_NUM"	int		NOT NULL,
	"REVIEW_NUM"	int		NULL,
	"TITLE"	varchar2(100)		NOT NULL,
	"CONTENT"	varchar2(2000)		NOT NULL,
	"AUTHORITY"	varchar2(20)		NULL,
	"WRITER"	varchar2(20)		NOT NULL,
	"REGDATE"	DATE		NOT NULL
);

CREATE TABLE "EDITOR" (
	"EDITOR_NUM"	int		NOT NULL,
	"TITLE"	varchar2(100)		NULL,
	"NUM_LIST"	varchar2(100)		NULL
);

CREATE TABLE "TAG" (
	"TAG_ID"	int		NOT NULL,
	"TAG_NAME"	varchar2(100)		NOT NULL,
	"COUNT"	int	DEFAULT 1	NOT NULL
);

CREATE TABLE "STORE_TAG" (
	"STORE_NUM"	int		NOT NULL,
	"TAG_ID"	int		NOT NULL
);

CREATE TABLE "REVIEW_TAG" (
	"REVIEW_NUM"	int		NOT NULL,
	"TAG_ID"	int		NOT NULL
);

CREATE TABLE "PICK" (
	"STORE_NUM"	int		NOT NULL,
	"ID"	varchar2(20)		NOT NULL
);

ALTER TABLE "STORE" ADD CONSTRAINT "PK_STORE" PRIMARY KEY (
	"STORE_NUM"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_NUM"
);

ALTER TABLE "REST_CAT" ADD CONSTRAINT "PK_REST_CAT" PRIMARY KEY (
	"STORE_NUM"
);

ALTER TABLE "CAFE_CAT" ADD CONSTRAINT "PK_CAFE_CAT" PRIMARY KEY (
	"STORE_NUM"
);

ALTER TABLE "WARNING" ADD CONSTRAINT "PK_WARNING" PRIMARY KEY (
	"WARNING_NUM"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NUM"
);

ALTER TABLE "EDITOR" ADD CONSTRAINT "PK_EDITOR" PRIMARY KEY (
	"EDITOR_NUM"
);

ALTER TABLE "TAG" ADD CONSTRAINT "PK_TAG" PRIMARY KEY (
	"TAG_ID"
);

ALTER TABLE "STORE" ADD CONSTRAINT "FK_MEMBER_TO_STORE_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_STORE_TO_REVIEW_1" FOREIGN KEY (
	"STORE_NUM"
)
REFERENCES "STORE" (
	"STORE_NUM"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "REST_CAT" ADD CONSTRAINT "FK_STORE_TO_REST_CAT_1" FOREIGN KEY (
	"STORE_NUM"
)
REFERENCES "STORE" (
	"STORE_NUM"
);

ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_STORE_TO_RESERVE_1" FOREIGN KEY (
	"STORE_NUM"
)
REFERENCES "STORE" (
	"STORE_NUM"
);

ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_MEMBER_TO_RESERVE_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "CAFE_CAT" ADD CONSTRAINT "FK_STORE_TO_CAFE_CAT_1" FOREIGN KEY (
	"STORE_NUM"
)
REFERENCES "STORE" (
	"STORE_NUM"
);

ALTER TABLE "WARNING" ADD CONSTRAINT "FK_REVIEW_TO_WARNING_1" FOREIGN KEY (
	"REVIEW_NUM"
)
REFERENCES "REVIEW" (
	"REVIEW_NUM"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_REVIEW_TO_NOTICE_1" FOREIGN KEY (
	"REVIEW_NUM"
)
REFERENCES "REVIEW" (
	"REVIEW_NUM"
);

ALTER TABLE "STORE_TAG" ADD CONSTRAINT "FK_STORE_TO_STORE_TAG_1" FOREIGN KEY (
	"STORE_NUM"
)
REFERENCES "STORE" (
	"STORE_NUM"
);

ALTER TABLE "STORE_TAG" ADD CONSTRAINT "FK_TAG_TO_STORE_TAG_1" FOREIGN KEY (
	"TAG_ID"
)
REFERENCES "TAG" (
	"TAG_ID"
);

ALTER TABLE "REVIEW_TAG" ADD CONSTRAINT "FK_REVIEW_TO_REVIEW_TAG_1" FOREIGN KEY (
	"REVIEW_NUM"
)
REFERENCES "REVIEW" (
	"REVIEW_NUM"
);

ALTER TABLE "REVIEW_TAG" ADD CONSTRAINT "FK_TAG_TO_REVIEW_TAG_1" FOREIGN KEY (
	"TAG_ID"
)
REFERENCES "TAG" (
	"TAG_ID"
);

ALTER TABLE "PICK" ADD CONSTRAINT "FK_STORE_TO_PICK_1" FOREIGN KEY (
	"STORE_NUM"
)
REFERENCES "STORE" (
	"STORE_NUM"
);

ALTER TABLE "PICK" ADD CONSTRAINT "FK_MEMBER_TO_PICK_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

